site_name: goal-jax

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - toc.follow

nav:
  - Home: index.md
  - API:
    - Geometry:
      - Manifold:
        - Manifolds: geometry/manifold/manifold.md
        - Submanifolds: geometry/manifold/subspace.md
        - Matrix Representations: geometry/manifold/matrix.md
        - Linear Maps: geometry/manifold/linear.md
        - Optimizers: geometry/manifold/optimizer.md
      - Exponential Family:
        - Exponential Families: geometry/exponential_family/exponential_family.md
        - Harmoniums: geometry/exponential_family/harmonium.md
        - Hierarchical Harmoniums: geometry/exponential_family/hierarchical.md
    - Models: 
      - Base:
        - Categorical: models/base/categorical.md
        - Poisson: models/base/poisson.md
        - Gaussian: 
          - Generalized Gaussians: models/base/gaussian/generalized.md
          - Normal: models/base/gaussian/normal.md
          - Boltzmann: models/base/gaussian/boltzmann.md
      - Graphical:
        - Mixture: models/graphical/mixture.md
        - Linear Gaussian Model: models/graphical/lgm.md
        - Hierarchical Mixture of Gaussians: models/graphical/hmog.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_source: false
            show_attribute_docstrings: true
            show_signatures: true
            show_type_annotations: true
            show_root_heading: true
            show_root_full_path: true
            members_order: source
            heading_level: 2
            docstring_style: google
            docstring_section_style: table
            # show_signature_annotations: False
            separate_signature: false
            filters: ["!^_"]
            preload_modules: [goal]
            auto_reference: true
            show_category_heading: true
            # Cross-reference settings
            enable_cross_reference: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 6
      anchorlink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition  # For note boxes
  - pymdownx.details  # For collapsible blocks
  # For proper cross-referencing
  - attr_list
  - md_in_html

# Add minimal CSS to adjust heading sizes while keeping ToC
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

watch:
  - src/goal
