site_name: goal-jax

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - toc.follow

nav:
  - Home: index.md
  - API:
    - Manifolds: manifold.md
    - Linear Maps: linear.md
    - Exponential Families:
      - Top-Level: exponential_family/core.md
      - Distributions: exponential_family/distributions.md
    - Harmoniums: harmonium.md


plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_source: false
            show_attribute_docstrings: true
            show_signatures: true
            show_type_annotations: true
            show_root_heading: true
            show_root_full_path: true
            members_order: source
            heading_level: 2
            docstring_style: google
            docstring_section_style: table
            # show_signature_annotations: False
            separate_signature: false
            filters: ["!^_"]
            preload_modules: [goal]
            auto_reference: true
            show_category_heading: true
            # Cross-reference settings
            enable_cross_reference: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 6
      anchorlink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition  # For note boxes
  - pymdownx.details  # For collapsible blocks
  # For proper cross-referencing
  - attr_list
  - md_in_html

# Add minimal CSS to adjust heading sizes while keeping ToC
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

watch:
  - src/goal
