site_name: goal-jax

theme:
  name: material
  features:
    # Remove if you don't want nested navigation
    - navigation.sections
    # These will give a flatter appearance
    - navigation.tabs
    - navigation.expand
    # This will make admonitions (note blocks) less prominent
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [.]  # search in current directory
          options:
            show_source: true
            show_root_heading: true
            show_root_full_path: true
            members_order: source
            heading_level: 1

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

watch:
  - goal  # Add your source directory to watch

nav:
  - Home: index.md
  - Reference:
      - Linear Operators: linear.md
      - Exponential Families: exponential_family.md
  # - Development: ""  # Section header
  #     - Contributing: contributing.md  # Future addition
